name: Update YouTube Stream Link

on:
  schedule:
    - cron: '0 */4 * * *' # প্রতি ৪ ঘণ্টা পরপর চলবে
  workflow_dispatch: # ম্যানুয়ালি রান করার অপশন

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yt-dlp

      - name: Run script
        run: python main.py

      - name: Commit and Push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add yt_link.txt
          git commit -m "Update live link" || exit 0
          git push
